### ISSUE TITLE
Sensor en poort kiezen vanuit UI

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/MindstormR#20]
Misschien is het een idee om vanuit de UI aan te geven welke sensors er zijn en op welke poort deze zijn aangesloten. We zouden in de tabel met sensor waardes dropdown lijsten kunnen opnemen.

**Comment by henkmollema** [comment]
cc @WesselKoorn

**Comment by Lg0enga** [comment]
@WesselKoorn Moet dit nog steeds even oppakken @henkmollema vind je ook niet?

**Comment by henkmollema** [comment]
Zeker! :+1:
