### ISSUE TITLE
Batterij percentage toevoegen aan de UI

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/MindstormR#23]
Batterij percentage kan je ophalen op deze url: `/robot/{id}/senors/get`

**Comment by WesselKoorn** [comment]
Kun je de percentages misschien afronden op hele getallen? @henkmollema

**Comment by henkmollema** [comment]
Ja, zal er ff naar kijken. Als het goed is zit dat er in bij de nieuwe versie.
